version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
     DATABASE_URL: postgresql://user:password@db:5432/testDB?schema=public

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: